version: '3.2'
services:
  psql:
    image: postgres:11
    environment:
      - POSTGRES_DB=notes

  node:
    container_name: react-todo-node
    build:
      context: ./
      dockerfile: Dockerfile-node
    tty: true
    ports:
      - 8080:8080
