version: '3.2'
services:
  psql:
    image: postgres:11
    environment:
      - POSTGRES_DB=notes

  node:
    container_name: react-todo-node
    build:
      context: ./
      dockerfile: Dockerfile-node
    tty: true
    volumes:
      - ./src/server.ts:/app/server.ts:Z
      - ./package.json:/app/package.json:Z
      - ./yarn.lock:/app/yarn.lock:Z
      - ./tsconfig.server.json:/app/tsconfig.json:Z
    ports:
      - 8080:8080
